### ISSUE TITLE
Support progressive enhancement of selects for users without JS

### ISSUE THREAD

**Issue by richardTowers** [alphagov/accessible-typeahead#25]
GOV.UK Verify are currently using https://github.com/JamieAppleseed/selectToAutocomplete in an alpha product. This is a jQuery plugin that takes a `select` tag as input and auto-magically transforms it into a typeahead.

The main advantage of this approach is that it makes the no-javascript fallback much easier to implement - you simply stamp out your `select` and `option` tags, and if the JS fails to run that's Good Enough(TM).

Of course it would still be possible to put a `select` in a `noscript` tag (or similar) to provide a no-javascript fallback while using `accesible-typeahead`, but the "provide a select and the plugin does the rest" is a nice workflow.

If you think that would be a nice feature I'd be happy to have a play and send you a PR. What do you think?

**Comment by tvararu** [comment]
(slow reply, was on leave)

Yes! I drafted a short spec in [this document at the end](https://github.com/openregister/rails-picker-example/blob/guide-data-file/guide-data-file.md):

```
⚠️ TODO: Allow the typeahead to enhance a `<select>` menu in-place.

The typeahead should have a `enhanceSelectEl` option which:

- Takes an existing <select> element
- Hides it visually and from screen readers
- Places a typeahead input field in the same place
- Hooks the typeahead to the select's <label> if it exists
- When a value is selected in the typeahead, update the hidden <select>
```

(might want a different name for the option)

If you want to build it then happy to review, otherwise I will get to this shortly as we need it ASAP.

For prior art, DWP already do this [in one of their prototypes](https://github.com/dwpdigitaltech/hrt-prototype/blob/master/app/assets/javascripts/modules/country-autocomplete.js#L119-L178) because they're using a different typeahead which doesn't have this option.

Only important thing I can think of: **do not remove the `<select>` menu until the typeahead has successfully initialised and rendered fully**. If you remove the select but a runtime error occurs and isn't caught, you could potentially have a situation where the typeahead fails to render, leaving the user high and dry.
