### ISSUE TITLE
Private styles? inline vs class?

### ISSUE THREAD

**Issue by nickcolley** [alphagov/accessible-typeahead#29]
I suppose you could argue that you only should expose things that can be themed so this may be fine?

https://github.com/alphagov/accessible-typeahead/blob/enhance-select-element/src/status.jsx#L42

**Comment by tvararu** [comment]
The aria status region uses inline styling to visually hide it. Everything else is [themed using regular CSS](https://github.com/alphagov/accessible-typeahead/blob/master/examples/styled.css).

This is intentional. Users can get confused why [stuff they don't expect to show up shows up](https://github.com/corejavascript/typeahead.js/pull/104#issuecomment-268482690) and not know how to fix it, when using other similar typeaheads.

Worth noting that the typeahead used to have a lot more inline styling relating to critical functionality and usability (like overlaying using absolute positioning), but it was abstracted out in the CSS.

There's pros and cons to either approach with some advocating that the best would be to just [pull everything into CSS](https://github.com/corejavascript/typeahead.js/pull/107#issuecomment-269791955) but I think the current way it works is alright.

**Comment by nickcolley** [comment]
Seems like current approach is good for users because consumers can't accidentally hide the information in an odd way but it means that this component must be updated which seems reasonable because then others have an easy way to update.
