### ISSUE TITLE
Don't provide a placeholder option

### ISSUE THREAD

**Issue by adamsilver** [alphagov/accessible-typeahead#41]
We shouldn't encourage the use of the placeholder attribute. Here's some details:

[https://govuk-elements.herokuapp.com/form-elements/#form-hint-text](https://govuk-elements.herokuapp.com/form-elements/#form-hint-text)

And some more details as to why:

[http://adamsilver.io/articles/placeholders-are-problematic/](http://adamsilver.io/articles/placeholders-are-problematic/)

**Comment by tvararu** [comment]
Hi @adamsilver, thanks for this. I thought about that exact bit of documentation when I added support for this option.

My intention for accessible-typeahead is for it to be a generic typeahead solution that anyone can use, not just Government, or for projects that subscribe to the GOVUK patterns. This is why I think the component should support it.

However, I definitely agree that `placeholder` is an anti-pattern.

Do you think that adding a notice to the option ("Do not use") with a link to the reasons against it would be sufficient, or do you think we should completely remove support for it?

**Comment by adamsilver** [comment]
I wouldn't (and I don't think GDS should) write code to support a feature that we don't recommend from a usability stand point.

If someone wants to do that, then let them fork or submit a PR (which we should reject :D).

**Comment by tvararu** [comment]
I'd like to keep this open so that @edwardhorsford can pitch in (as he's the designer for this component), but my hunch would still be to support it. I think not having it would hurt adoption outside of Government, albeit at a minor level. Forking doesn't work well because then you are asking people to take on a certain maintenance responsibility, and it makes it more difficult to adopt new improvements to the component.

I am however keen on documenting the reasons not to use it prominently regardless of whether the feature is supported or not.

**Comment by tvararu** [comment]
I'd like to make a decision on this for `v1.0.0.`

I think we should support the option and caution against it in the README because:

- People can use this without necessarily consenting to every GDS pattern.
- Stops people from asking about it in the future.
- Stops people from forking the repository to add support for a feature, fragmenting the user base.

There's prior art with [other libraries supporting options they don't like](https://facebook.github.io/react/docs/dom-elements.html#dangerouslysetinnerhtml) but naming them silly things just to make sure the users are aware of the issues. I don't think we should do this, but happy to warn against it in the README.
